import { Sofia_Sans } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import DesText from "@/components/DesText";
import CollPreview from "@/components/CollPreview";
import ShopByCategory from "@/components/ShopByCategory";
import Hero from "@/components/Hero";
import ModelShow from "@/components/ModelShow";
import PopularView from "@/components/PopularView";
import InfoModel from "@/components/InfoModel";
import NewsLetter from "@/components/NewsLetter";

const SofiaSans = Sofia_Sans({
  weight: "500",
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "BI~NI home",
  description: "Generated by create next app",
  themeColor: "#fff",
};
export default function Home() {
  return (
    <>
      <div className={SofiaSans.className}>
        <Hero />
        <DesText />
        <ModelShow />
        <ShopByCategory /> 
        <PopularView />
        <InfoModel />
        <CollPreview />
      </div>
    </>
  );
}
