
import { ProductInterface } from "./Interfaces/ProductInterface";

export const productList: ProductInterface[] = [
    {
      name: "Diamond Necklace",
      image: "/ProImages/clash_1.jpg",
      price: 19.99,
      currency: "USD",
      description: "Description of Diamond Necklace",
      size: 10,
      type: "Type 1",
      id: "product1",
    },
    {
      name: "Emerald Ring",
      image: "/ProImages/love_1.jpg",
      price: 24.99,
      currency: "USD",
      description: "Description of Emerald Ring",
      size: 8,
      type: "Type 2",
      id: "product2",
    },
    {
      name: "Sapphire Earrings",
      image: "/ProImages/trinity_1.jpg",
      price: 12.99,
      currency: "USD",
      description: "Description of Sapphire Earrings",
      size: 12,
      type: "Type 1",
      id: "product3",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/brace_1.jpg",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product4",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/brace_1.jpg",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product5",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/C1.webp",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product6",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/C2.webp",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product7",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/C3.webp",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product8",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/C5.webp",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product9",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/C4.webp",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product10",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/C1.webp",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product11",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/C6.webp",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product12",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/C5.webp",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product13",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/C4.webp",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product14",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/C3.webp",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product15",
    },
    {
      name: "Ruby Bracelet",
      image: "/ProImages/C2.webp",
      price: 100.99,
      currency: "USD",
      description: "Description of Ruby Bracelet",
      size: 12,
      type: "Type 1",
      id: "product16",
    },
    // Rest of the products...
  ];
